### PR TITLE
Adding podspec

### PR DESCRIPTION
**Pull request by marcelofabri**
It'd be nice to have a tag too and then push this to trunk.

### CODE REVIEW

**Comment by groue** [comment]
Hi Marcelo!

Thanks for this podspec. Last time I tried to write one, a few weeks ago, cocoapods used to fail building the framework, because it could not compile the Obj-C file Mustache/Rendering/GRMustacheKeyAccess.m.

So: did you test if your podspec can actually be successfully integrated? If so, I'll happily integrate it :smile:!

About the tag, I'm afraid I can not go with 1.0.0 yet. I'll go with 0.9.0 though, to show that the API is almost complete and stable.

The last TODO item that needs a solution before 1.0.0 is the one below, and it is unfortunately rather tricky to achieve while maintaining a nice public API:

> Let user easily override default key lookup (maybe expose and make mutable MustacheBox.keyedSubscript ?). The goal is to provide a good solution to https://github.com/groue/GRMustache/issues/66

**Comment by marcelofabri** [comment]
I tested it in a project successfully (running a simple example from README).

**Comment by groue** [comment]
OK, so it looks like cocoapods was fixed, or that your podspec is better than mine :-)

Should `s.ios.deployment_target` be 7.0 (since Swift code is supposed to run on iOS 7), or does it need to stay at 8.0 (since support for frameworks was only added in iOS 8)?

**Comment by marcelofabri** [comment]
Yeah, it needs to be 8 because of dynamic frameworks.

**Comment by groue** [comment]
Thanks a lot for your contribution, Marcelo.

Happy Mustache!

**Comment by groue** [comment]
Looks like GRMustache.swift cocoapod is alive:

```
$ pod trunk push GRMustache.swift.podspec 
Validating podspec
 -> GRMustache.swift (0.9.0)
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/b89e54a38ee85898357e547919bb6e3caaf6e861/Specs/GRMustache.swift/0.9.0/GRMustache.swift.podspec.json
  - Log messages:
    - May 12th, 17:14: Push for `GRMustache.swift 0.9.0' initiated.
    - May 12th, 17:14: Push for `GRMustache.swift 0.9.0' has been pushed (1.508138897 s).
```

**Comment by marcelofabri** [comment]
:+1:

**Pull request merged**
