### PR TITLE
Swift4 support

### PR DESCRIPTION
**Pull request by maximkhatskevich**
Made various fixes to fully support Swift 4.

### CODE REVIEW

**Comment by liamjones** [comment]
@groue Any chance of this PR or #46 being merged soon? Currently we're having to maintain a private fork of GRMustache.swift for Swift 4 support

**Comment by AlkiviadisPapadakis-je** [comment]
Any update on this please?

**Comment by gelliott181** [comment]
@groue is there anything we as your community can do to help you land these changes? Swift 4 has been available for nearly a year and there are multiple PRs with Swift 4 support. There also hasn't been a commit to master in 4 months, and the latest tag is even older. 

Many, many people have put in work to bring GRMustache.swift to Swift 4. There are a number of forks that have been updated to allow others to continue working, easily visible on your network graph (https://github.com/groue/GRMustache.swift/network). I'm sure there are people who would be willing to help maintain the official repo if it's no longer possible for you to do so as an individual. Do we need to be concerned that GRMustache.swift is abandoned or dead?

**Comment by fumito-ito** [comment]
merged as #57 . thanks!

**Pull request closed without merging**
