### PR TITLE
Fix string interpolation issues with optionals

### PR DESCRIPTION
**Pull request by saagarjha**

### CODE REVIEW

**Comment by groue** [comment]
Hello @saagarjha 

Please provide a proper bug report, and why your PR is the correct solution to this bug.

**Comment by saagarjha** [comment]
Sure (would you like me to file an issue?). Basically, GRMustache.swift will build with warnings with the latest version of Xcode because of the adoption of the Harlan Haskins's "proposal" [Disallow Optionals in String Interpolation Segments](https://gist.github.com/harlanhaskins/63b7343e7fe4e5f4c6cfbe9413a98fdd), which argued that the default representation for `Optional` produced the surprising result of `Optional("value")` when interpolated. I've migrated the direct interpolation of `Optional`s to instead produce their description if non-`nil` and `"nil"` if not, which satisfies the compiler and provides what I feel is a reasonable default. If you feel differently, please let me know and I'll make update my pull request.

**Comment by groue** [comment]
> Basically, GRMustache.swift **will** build [...]

Understood. Is the [proposal](https://gist.github.com/harlanhaskins/63b7343e7fe4e5f4c6cfbe9413a98fdd) accepted yet?

**Comment by saagarjha** [comment]
It wasn't really accepted, but it was agreed upon almost unanimously and implemented without a formal review.

**Comment by groue** [comment]
> It wasn't really accepted, but it was agreed upon almost unanimously and implemented without a formal review.

Cool. So your PR looks like the right thing to do. But it's not really. Since we're building a debugging string, I'd rather see `box.value.map { String(reflecting: $0) } ?? "nil"` instead of a plain `box.value ?? "nil"` that makes the compiler happy but doesn't care about humans.

**Comment by saagarjha** [comment]
Sure thing.

**Comment by groue** [comment]
Great! Many thanks, @saagarjha 👍

**Pull request merged**
