### PR TITLE
Update to Swift 4

### PR DESCRIPTION
**Pull request by saagarjha**
I've run GRMustache.swift through Xcode 9's Swift converter and made changes accordingly. You might want to glance through it, though, since I changed some code slightly.

### CODE REVIEW

**Comment by idev4u** [comment]
@groue I would also be interested to have an compatible version for swift 4. Is there a reason why you not integrate this PR? Can I support you with work?

**Comment by ajaysubramanya26** [comment]
Hello maintainers, thank you for this swift port of mustache, we've just started using this, and found it to work perfectly. However, we now have to move our project to swift 4 because some of our dependencies are up to swift 4 now. Is there any plan to get this into master? 

Also, please let me know if you need any help with this. 

Thanks again.

**Comment by moray95** [comment]
It really sad that all Mustache implementations for Swift seems to be dead to the point of not even accepting a PR. For anyone interested, I have forked @saagarjha's repo and published to CocoaPods under the name [GRMustache.swift4](http://cocoapods.org/pods/GRMustache.swift4). Thank you @saagarjha for the work you provided.

**Comment by fumito-ito** [comment]
merged as #57 . thanks!

**Pull request closed without merging**
