### PR TITLE
fix: update Foundation.swift for cocoa pods

### PR DESCRIPTION
**Pull request by TheRogue76**
Bit of a doozy, but basically, when it comes to SPM, the `GRMustacheKeyAccess` is a package that you import, but when it comes to Cocoapods, this is already bundled next to it and is NOT a separate package, so when you call import, it will fail, which means you can't build when using cocoa pods.

This PR adds a check to see if that even exists before trying to import it, addressing the issue for both SPM and Cocoapods (tried both locally but feel free to try as well)

### CODE REVIEW

**Comment by TheRogue76** [comment]
@fumito-ito can you check this as well?

**Comment by fumito-ito** [comment]
@TheRogue76 Thanks for your PR. However, I encountered an error when running pod lib lint --allow-warnings on my macOS. The error message is as follows:

```sh
NOTE  | [iOS] xcodebuild:  clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode-16.0.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; try increasing the minimum deployment target
```

It seems similar to this issue: https://github.com/CocoaPods/CocoaPods/issues/11839.

**Comment by TheRogue76** [comment]
@fumito-ito Interesting. I will try to find some time this weekend / tomorrow and try seeing what is going on and report back. Seems like a removed dependency on newer tool chains.

**Comment by TheRogue76** [comment]
Ok @fumito-ito It appears that the matter is due to Xcode deprecating the older targets. As mentioned [by Apple here](https://forums.developer.apple.com/forums/thread/728021?answerId=752314022#752314022) Bumping the target to iOS 11 is now a requirement. I am bumping it on the pod file as well in this PR just to be in sync. Let me know your thoughts.
Screenshot 2024-10-25 at 11 22 23

**Comment by fumito-ito** [comment]
Thanks @TheRogue76 . I believe raising the target is a reasonable change. I will update the SPM target, but I will create a separate PR for that myself.

**Review by fumito-ito — APPROVED** [review]

**Pull request merged**
