### PR TITLE
Reduce iOS Deployment Target to 8.0

### PR DESCRIPTION
**Pull request by ObjColumnist**

### CODE REVIEW

**Comment by ObjColumnist** [comment]
I noticed when using Carthage that the Deployment Target was 8.0, but I couldn't see any reason for this?

**Comment by groue** [comment]
Hello Spencer.

This 8.1 deployment target comes from https://github.com/groue/GRMustache.swift/pull/6#issuecomment-103163703, an issue which was specifically opened about Carthage support.

Do you confirm 8.0 is OK with Carthage?

**Comment by ObjColumnist** [comment]
Hi @groue,

Using Carthage 0.8.0 (the latest version) I had no issues compiling with my fork, and the this was the only change.

**Comment by ikesyo** [comment]
There is no reason for Carthage to require 8.1 deployment target, 8.0 should be OK (I'm a Carthage collaborator).

**Comment by ikesyo** [comment]
OS X 10.9 should be OK too. :wink: [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) which is Carthage compatible [has 8.0/10.9 deployment targets](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/27d069a795dd7bb9c2bb1e8d9c4b382e90c5dca0/ReactiveCocoa.xcodeproj/project.pbxproj#L1992-L1993).

**Comment by groue** [comment]
All right, folks, thanks for your reassuring comments!

**Pull request merged**
