### PR TITLE
Upgrade swift version to Swift 5 and some fixes

### PR DESCRIPTION
**Pull request by fumito-ito**
This PR offers following updates.

- upgrade swift to Swift 5
- fix runtime crash on Xcode 10 via https://github.com/groue/GRMustache.swift/pull/53
- remove invalid tests for Swift via https://github.com/groue/GRMustache.swift/pull/39

### CODE REVIEW

**Comment by sburlewapg** [comment]
Thank you for doing this!! @groue can this get merged if everything looks fine?

**Comment by groue** [comment]
Hello @fumito-ito,

I gave a look at your PR, and it looks fine to me. I also see that you did already support Swift 4.0 and Swift 4.2 in the past.

I have invited you as a repository contributor. Feel right at home: I give you the keys 🤝🎁🔑.

Please also send me the email you would like to use for `pod trunk push`!

**Comment by groue** [comment]
PS: I don't feel like maintaining GRMustache.swift these days, as you have noticed. But if you have any question I will do my best transmitting any useful information.

**Comment by gelliott181** [comment]
@groue thanks for keeping this going by passing off some responsibility, and @fumito-ito thanks for taking up the slack here!

**Comment by groue** [comment]
It was a long overdue. I owe apologies to everyone. Thank you all for your patience!

**Pull request merged**
